/* ---------------------------------------------------------------
   HAND-WRITTEN NOTES for lines, by opening id and line id.
   The line data itself is generated from tools/repertoire.seed.mjs by
   tools/verify-repertoire.mjs; this file survives regeneration.
   Numbers quoted: Stockfish 18 depth 18 from YOUR point of view, and
   Lichess 1400-1800 blitz/rapid shares ("plays X here 42%").
--------------------------------------------------------------- */
export const NOTES = {
  scotch: {
    main: 'The Max Lange Attack — masters’ most-played move at every step (Wells; Dembo & Palliser). Level but lively. 6.Bb5 pins, 7.Nxd4 regains the pawn, then f3 asks the knight where it is going.',
    'max-lange-be7': 'After the trade on c6 Black often plays 9…Be7 (17%) instead of …Bc5. Same plan: f3 to hit the knight, Be3, and play against the c-pawns.',
    'max-lange-bxc6': 'Black recaptures with the bishop (19%) to keep the pawns healthy. Castle; the bishop on c6 is a target for Nxc6 and the knight on e4 still needs a home.',
    'max-lange-bc5': 'Black develops the bishop before …Bd7 (23%) and then castles (51%). Be3 offers the trade; play continues as in the main line with the bishops swapped.',
    'max-lange-nd7': '6…Nd7 (12%) covers the knight instead of jumping to e4. Take on d4 and castle; the pin on c6 stays.',
    ng4: 'The knight jumps to g4 (23%) instead of d5. Castle first; the e5 pawn and the f7 square stay under pressure. (6.Qe2 tested −0.7.)',
    ne4: 'The knight sits on e4 (12%) and Black shores it up with …d5 (34%). Qe2 first, then take on d4 and castle; the knight has no retreat squares.',
    'ne4-nc5': 'After Qe2 the knight retreats to c5. Castle and the d4 pawn is coming back.',
    qe7: 'A pin along the e-file that club players love (12%) and masters never play. Castle: the queen on e7 blocks Black’s own bishop and the pin achieves nothing.',
    haxo: 'The Haxo Gambit, your most common surprise (8 games). 5.c3 offers the pawn back; 5…Nf6 (27%) is Black’s sound answer and reaches the classical Giuoco Piano. 7.Bd2 (not the old Møller 7.Nc3, tested −0.5) then Qb3 — a known, level main line.',
    'haxo-oo': 'In the Giuoco Piano Black castles early (42%) rather than striking with …d5. Castle too and play e5 or Re1 against the knight on f6.',
    'haxo-na5': 'The knight harasses the queen: 10…Na5 (30%) 11.Qa4+ Nc6. Do not repeat — the engine finds the way out and keeps the initiative.',
    'haxo-nxe4': 'Greco Gambit accepted: 7…Nxe4 (28%). The forcing line 8.Bxb4 Nxb4 9.Bxf7+ Kxf7 10.Qb3+ d5 11.Qxb4 regains everything; Black’s king has lost the right to castle.',
    'haxo-bb6': 'Black keeps the bishop with 6…Bb6. Push e5 (tested best) and the knight on f6 must jump; Black’s bishop bites on granite.',
    'haxo-trap': 'The club trap: 5…dxc3 is the most common move here (55%!) and 6.Bxf7+! Kxf7 7.Qd5+ follows. Most players run to e8 (78%): 8.Qh5+ and the bishop on c5 falls. Objectively near equal, but far easier for White and a king in the middle.',
    'haxo-trap-kf8': 'The same trap with 7…Kf8 (22%): 8.Qxc5+ d6 9.Qxc3 — material back, Black cannot castle.',
    london: 'The London Defence (4…Bb4+, 8%): Black grabs on c3 and after 6.bxc3 Ba5 you have a big lead in development for the pawn. Black’s most common follow-up is 7…Nge7 (29%).',
    'london-nf6': 'The other London try, 7…Nf6 (20%). Develop with Re1 and e5 in mind; the a5 bishop is out of play.',
    'london-be7': '6…Be7 (16%) walks into 7.Qd5: f7 and b7 attacked at once. (Chess Doctrine; engine-checked.)',
    'london-trap': '6…Bc5? drops into the Bxf7+ fork: 7.Bxf7+ Kxf7 8.Qd5+ and 9.Qxc5. Most run to e8 (75%).',
    'london-trap-kf8': 'Same fork after 8…Kf8: Qxc5+ and Qc4. A clean extra piece.',
    hungarian: '4…Be7 declines (8%). Take on d4 and you have a normal Scotch with more space; h3 stops …Bg4/…Ng4 tricks.',
    'hungarian-nxd4': 'After 5.Nxd4 a third of players trade at once (32%). Recapture with the queen — it is safe on d4 and centralised.',
    'declined-d6': '4…d6 also returns the pawn (13%). Same plan: Nxd4, develop, h3, and meet …Be6 with Bxe6.',
    'declined-d6-nxd4': 'Half of club players trade knights here (52%). 6.Qxd4 — a strong centralised queen that cannot be chased.',
    'declined-d6-ne5': 'The knight hits your bishop with 8…Ne5 (28%). Retreat it and keep the extra space; the knight is a target for f4.',
    h6: 'A wasted move but not a losing one (tested +0.3), and popular (18%). Take the centre: Nxd4, trade on c6, e5.',
    'h6-nxd4': 'Again the knight trade (49%). 6.Qxd4 with a free hand in the centre.',
    'qf6-4': 'Early queen. Castle; after the usual 5…Bc5 (47%) play c3 and Qb3 — the queen on f6 blocks Black’s own knight.',
    'scotch-d6': '3…d6 (10 of your games). Push d5: the knight must retreat to e7, then c4 and Nc3 give you a big centre. Black’s most common reply is 5…Nf6 (21%).',
    'scotch-d6-nb8': 'The knight goes all the way home (13%). c4 and Nc3: you own the centre and Black has undeveloped.',
    'scotch-d6-nd4': 'The knight jumps to d4 (12%) and is simply traded: Nxd4 exd4 Qxd4, a free centralised queen.',
    lolli: '3…Nxd4 trades the developed knight. 5.Qxd4 — the queen cannot be chased with …Nc6 any more. Club players follow with 5…d6 (35%).',
    f5: 'A Latvian-style lunge (rare, but two of your games). Take on e5, take back, and after …fxe4 Black’s king is open. (6.Qh5+ tested −0.7; develop with Nc3 instead.)',
    bd6: 'The bishop blocks its own d-pawn. d5 and c4: Black’s queenside never gets out.',
    'qf6-3': 'd5! hits the knight while the queen stands in the way of Black’s development. (4.Bg5 tested −0.8.)',
    'bb4-3': 'c3 kicks the bishop; most retreat to d6 (27%), then d5 cramps the knight. Black has lost time and the centre.',
  },
  elephant: {
    main: 'The Paulsen Countergambit against White’s best: 4.Qe2! 5.d3 6.Nbd2. Black is a pawn down (about −0.5 — the honest price of this gambit) but gets the pieces out fast and regains the pawn with …Qxe4. Know it cold; this is what strong opponents play.',
    'nc3-5': '5.Nc3 (34%, masters 47%) avoids the pin on the e-file. Develop with Be7, castle, and after 7.d3 (masters’ choice) play for activity.',
    'nc3-5-nxf6': 'White trades on f6 first. Recapture with the bishop; the two bishops give Black play for the pawn.',
    'nc3-6': 'Against 6.Nc3 (39%) the key move is 6…Bb4! — pin, trade on c3 and castle. Half of club players then take on f6 (51%); the doubled f-pawns are fine, the bishop pair is not.',
    'dxe4-6': 'White trades queens early (49%). Recapture with the knight, meet Bd3 with …Nc5; against the common 9.Bc4 (40%) develop and play …Be6.',
    ng5: '5.Ng5 wants e4 (10%). …Be7 kicks it while developing; castle quickly.',
    nd4: '4.Nd4 (29%, 5 of your games): take on d5 and centralise. The master move is 5.Nb3; the queen is well placed and Black develops with …Nc6, …Nf6.',
    'nd4-c3': 'After 5.c3 Nc6 most amateurs take: 6.Nxc6 (60%). Recapture with the queen and you are fully developed for the pawn.',
    ne5: '4.Ne5 (7%, 3 of your games). Take on d5 — the queen hits the knight too. After 5.d4 take en passant and develop.',
    ng1: 'Full retreat (19% of club games, 8 of yours!). Take the pawn back; White’s usual 5.Nc3 (70%) is met by developing with tempo. Level after best play, but two tempi are a lot at club level.',
    bb5: '4.Bb5+ — block with the pawn, not the bishop: …c6, and after the trades White’s best is 6.Qe2. Black is fully developed and scores 63% here in practice.',
    nxe5: '3.Nxe5 (19%, masters 30%; 8 of your games): hit the knight with 3…Bd6 — masters’ 63% choice and your own habit. Tested at depth 22 it beats 3…dxe4 (which 4.Bc4! refutes). 5.Bc4 is one of three common 5th moves.',
    'nxe5-nc4': 'The master way: 5.Nc4 (39% of master games) hits your bishop. Take or retreat — the engine finishes the line; about level.',
    'nxe5-nc3': 'The most common club move, 5.Nc3 (22%). Develop with …Nf6 and castle; the e4 pawn is a strength as long as it is defended.',
    'nxe5-nf3': 'The knight simply goes home. Take on e4 and you have regained the pawn with a lead in development.',
    nc4: 'The knight wanders to c4 where it is a target. Develop with tempo; Black is at least equal, a pawn up in activity.',
    nxf7: '4.Nxf7 takes the fork at once. It scores 60% for Black in practice: after the trades White’s king is the one in trouble. Follow the engine line.',
    d4: '3.d4 strikes first (masters 21%). Take on e4, meet Nxe5 with …Nd7, trade and develop; 6.Nc3 (35%) is the usual continuation.',
    d3: 'Quiet 3.d3. Take, trade queens on d1, and you are level with easy play. 6.Bd3 (41%) is what you will see most.',
    'd3-nxe5': 'After 3.d3 dxe4 many take on e5 (30%). Regain the pawn with …dxe4 already in hand; develop and the e-file opens for you.',
    'nc3-3': '3.Nc3: take on e4 and develop; 5.Bc4 (23%) is met by …Be6 or …Bf5 as the engine shows.',
    bd3: 'The bishop on d3 blocks White’s own d-pawn (rare, but two of your games). Take on e4 and hit the bishop with …f5 — after 6.Qe2 (66%) White is tangled.',
  },
};
