/* GENERATED by tools/verify-repertoire.mjs on 2026-09-17 from tools/repertoire.seed.mjs, Stockfish 18 depth 18.
   Do not edit by hand: edit the seed, re-run, then adjust js/notes.js. */
export default [
  {
    "id": "scotch",
    "name": "Scotch Gambit",
    "side": "w",
    "signaturePlies": 5,
    "lines": [
      {
        "id": "main",
        "name": "Max Lange Attack",
        "kind": "main",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "Nc6",
          "d4",
          "exd4",
          "Bc4",
          "Nf6",
          "e5",
          "d5",
          "Bb5",
          "Ne4",
          "Nxd4",
          "Bd7",
          "Bxc6",
          "bxc6",
          "O-O",
          "Bc5",
          "f3",
          "Ng5",
          "Be3"
        ],
        "cp": -3,
        "evals": [
          {
            "ply": 0,
            "san": "e4",
            "cp": 35
          },
          {
            "ply": 2,
            "san": "Nf3",
            "cp": 38
          },
          {
            "ply": 4,
            "san": "d4",
            "cp": 33
          },
          {
            "ply": 6,
            "san": "Bc4",
            "cp": 10
          },
          {
            "ply": 8,
            "san": "e5",
            "cp": 10
          },
          {
            "ply": 10,
            "san": "Bb5",
            "cp": 9
          },
          {
            "ply": 12,
            "san": "Nxd4",
            "cp": 14
          },
          {
            "ply": 14,
            "san": "Bxc6",
            "cp": 8
          },
          {
            "ply": 16,
            "san": "O-O",
            "cp": 3
          },
          {
            "ply": 18,
            "san": "f3",
            "cp": 16
          },
          {
            "ply": 20,
            "san": "Be3",
            "cp": -3
          }
        ],
        "sources": [
          "W-Scotch",
          "CD",
          "Lichess"
        ]
      },
      {
        "id": "max-lange-bc5",
        "name": "Max Lange, 7...Bc5",
        "kind": "main",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "Nc6",
          "d4",
          "exd4",
          "Bc4",
          "Nf6",
          "e5",
          "d5",
          "Bb5",
          "Ne4",
          "Nxd4",
          "Bc5",
          "Be3",
          "Bd7",
          "Bxc6",
          "bxc6",
          "O-O",
          "O-O",
          "f3",
          "Ng5"
        ],
        "deviatesAt": 13,
        "cp": 0,
        "evals": [
          {
            "ply": 0,
            "san": "e4",
            "cp": 35
          },
          {
            "ply": 2,
            "san": "Nf3",
            "cp": 38
          },
          {
            "ply": 4,
            "san": "d4",
            "cp": 33
          },
          {
            "ply": 6,
            "san": "Bc4",
            "cp": 10
          },
          {
            "ply": 8,
            "san": "e5",
            "cp": 10
          },
          {
            "ply": 10,
            "san": "Bb5",
            "cp": 9
          },
          {
            "ply": 12,
            "san": "Nxd4",
            "cp": 14
          },
          {
            "ply": 14,
            "san": "Be3",
            "cp": 20
          },
          {
            "ply": 16,
            "san": "Bxc6",
            "cp": 23
          },
          {
            "ply": 18,
            "san": "O-O",
            "cp": -15
          },
          {
            "ply": 20,
            "san": "f3",
            "cp": 0
          }
        ],
        "sources": [
          "Lichess"
        ]
      },
      {
        "id": "ng4",
        "name": "5...Ng4",
        "kind": "main",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "Nc6",
          "d4",
          "exd4",
          "Bc4",
          "Nf6",
          "e5",
          "Ng4",
          "O-O",
          "Be7",
          "Re1",
          "d6",
          "exd6",
          "cxd6"
        ],
        "deviatesAt": 9,
        "cp": 28,
        "evals": [
          {
            "ply": 0,
            "san": "e4",
            "cp": 35
          },
          {
            "ply": 2,
            "san": "Nf3",
            "cp": 38
          },
          {
            "ply": 4,
            "san": "d4",
            "cp": 33
          },
          {
            "ply": 6,
            "san": "Bc4",
            "cp": 10
          },
          {
            "ply": 8,
            "san": "e5",
            "cp": 10
          },
          {
            "ply": 10,
            "san": "O-O",
            "cp": 28
          },
          {
            "ply": 12,
            "san": "Re1",
            "cp": 25
          },
          {
            "ply": 14,
            "san": "exd6",
            "cp": 28
          }
        ],
        "sources": [
          "W-Scotch",
          "Lichess",
          "SF"
        ]
      },
      {
        "id": "ne4",
        "name": "5...Ne4",
        "kind": "main",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "Nc6",
          "d4",
          "exd4",
          "Bc4",
          "Nf6",
          "e5",
          "Ne4",
          "Qe2",
          "Nc5",
          "O-O",
          "Ne6",
          "c3",
          "d5"
        ],
        "deviatesAt": 9,
        "cp": 9,
        "evals": [
          {
            "ply": 0,
            "san": "e4",
            "cp": 35
          },
          {
            "ply": 2,
            "san": "Nf3",
            "cp": 38
          },
          {
            "ply": 4,
            "san": "d4",
            "cp": 33
          },
          {
            "ply": 6,
            "san": "Bc4",
            "cp": 10
          },
          {
            "ply": 8,
            "san": "e5",
            "cp": 10
          },
          {
            "ply": 10,
            "san": "Qe2",
            "cp": 14
          },
          {
            "ply": 12,
            "san": "O-O",
            "cp": -3
          },
          {
            "ply": 14,
            "san": "c3",
            "cp": 9
          }
        ],
        "sources": [
          "Lichess",
          "Games",
          "SF"
        ]
      },
      {
        "id": "haxo",
        "name": "Haxo Gambit → Giuoco Piano, 7.Bd2",
        "kind": "main",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "Nc6",
          "d4",
          "exd4",
          "Bc4",
          "Bc5",
          "c3",
          "Nf6",
          "cxd4",
          "Bb4+",
          "Bd2",
          "Bxd2+",
          "Nbxd2",
          "d5",
          "exd5",
          "Nxd5",
          "Qb3",
          "Nce7",
          "O-O",
          "O-O",
          "Rfe1",
          "c6"
        ],
        "deviatesAt": 7,
        "cp": 23,
        "evals": [
          {
            "ply": 0,
            "san": "e4",
            "cp": 35
          },
          {
            "ply": 2,
            "san": "Nf3",
            "cp": 38
          },
          {
            "ply": 4,
            "san": "d4",
            "cp": 33
          },
          {
            "ply": 6,
            "san": "Bc4",
            "cp": 10
          },
          {
            "ply": 8,
            "san": "c3",
            "cp": -2
          },
          {
            "ply": 10,
            "san": "cxd4",
            "cp": 0
          },
          {
            "ply": 12,
            "san": "Bd2",
            "cp": 0
          },
          {
            "ply": 14,
            "san": "Nbxd2",
            "cp": 0
          },
          {
            "ply": 16,
            "san": "exd5",
            "cp": 0
          },
          {
            "ply": 18,
            "san": "Qb3",
            "cp": 0
          },
          {
            "ply": 20,
            "san": "O-O",
            "cp": 24
          },
          {
            "ply": 22,
            "san": "Rfe1",
            "cp": 23
          }
        ],
        "sources": [
          "W-Scotch",
          "CD"
        ]
      },
      {
        "id": "haxo-bb6",
        "name": "Haxo Gambit, 6...Bb6",
        "kind": "main",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "Nc6",
          "d4",
          "exd4",
          "Bc4",
          "Bc5",
          "c3",
          "Nf6",
          "cxd4",
          "Bb6",
          "e5",
          "Ne4",
          "Qe2",
          "d5"
        ],
        "deviatesAt": 7,
        "cp": 154,
        "evals": [
          {
            "ply": 0,
            "san": "e4",
            "cp": 35
          },
          {
            "ply": 2,
            "san": "Nf3",
            "cp": 38
          },
          {
            "ply": 4,
            "san": "d4",
            "cp": 33
          },
          {
            "ply": 6,
            "san": "Bc4",
            "cp": 10
          },
          {
            "ply": 8,
            "san": "c3",
            "cp": -2
          },
          {
            "ply": 10,
            "san": "cxd4",
            "cp": 0
          },
          {
            "ply": 12,
            "san": "e5",
            "cp": 134
          },
          {
            "ply": 14,
            "san": "Qe2",
            "cp": 154
          }
        ],
        "sources": [
          "W-Scotch",
          "SF"
        ]
      },
      {
        "id": "london",
        "name": "London Defence (4...Bb4+)",
        "kind": "main",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "Nc6",
          "d4",
          "exd4",
          "Bc4",
          "Bb4+",
          "c3",
          "dxc3",
          "bxc3",
          "Ba5",
          "O-O",
          "d6",
          "Qb3",
          "Qd7"
        ],
        "deviatesAt": 7,
        "cp": 10,
        "evals": [
          {
            "ply": 0,
            "san": "e4",
            "cp": 35
          },
          {
            "ply": 2,
            "san": "Nf3",
            "cp": 38
          },
          {
            "ply": 4,
            "san": "d4",
            "cp": 33
          },
          {
            "ply": 6,
            "san": "Bc4",
            "cp": 10
          },
          {
            "ply": 8,
            "san": "c3",
            "cp": 0
          },
          {
            "ply": 10,
            "san": "bxc3",
            "cp": -8
          },
          {
            "ply": 12,
            "san": "O-O",
            "cp": -13
          },
          {
            "ply": 14,
            "san": "Qb3",
            "cp": 10
          }
        ],
        "sources": [
          "W-Scotch",
          "CD",
          "SF"
        ]
      },
      {
        "id": "hungarian",
        "name": "Hungarian Defence (4...Be7)",
        "kind": "main",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "Nc6",
          "d4",
          "exd4",
          "Bc4",
          "Be7",
          "Nxd4",
          "d6",
          "O-O",
          "Nf6",
          "Nc3",
          "O-O",
          "h3",
          "Nxd4",
          "Qxd4",
          "Be6",
          "Bxe6",
          "fxe6"
        ],
        "deviatesAt": 7,
        "cp": 35,
        "evals": [
          {
            "ply": 0,
            "san": "e4",
            "cp": 35
          },
          {
            "ply": 2,
            "san": "Nf3",
            "cp": 38
          },
          {
            "ply": 4,
            "san": "d4",
            "cp": 33
          },
          {
            "ply": 6,
            "san": "Bc4",
            "cp": 10
          },
          {
            "ply": 8,
            "san": "Nxd4",
            "cp": 45
          },
          {
            "ply": 10,
            "san": "O-O",
            "cp": 46
          },
          {
            "ply": 12,
            "san": "Nc3",
            "cp": 47
          },
          {
            "ply": 14,
            "san": "h3",
            "cp": 46
          },
          {
            "ply": 16,
            "san": "Qxd4",
            "cp": 37
          },
          {
            "ply": 18,
            "san": "Bxe6",
            "cp": 35
          }
        ],
        "sources": [
          "W-Scotch",
          "CD"
        ]
      },
      {
        "id": "declined-d6",
        "name": "4...d6 (gambit declined)",
        "kind": "main",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "Nc6",
          "d4",
          "exd4",
          "Bc4",
          "d6",
          "Nxd4",
          "Nf6",
          "Nc3",
          "Be7",
          "O-O",
          "O-O",
          "h3",
          "Nxd4",
          "Qxd4",
          "Be6",
          "Bxe6",
          "fxe6"
        ],
        "deviatesAt": 7,
        "cp": 24,
        "evals": [
          {
            "ply": 0,
            "san": "e4",
            "cp": 35
          },
          {
            "ply": 2,
            "san": "Nf3",
            "cp": 38
          },
          {
            "ply": 4,
            "san": "d4",
            "cp": 33
          },
          {
            "ply": 6,
            "san": "Bc4",
            "cp": 10
          },
          {
            "ply": 8,
            "san": "Nxd4",
            "cp": 46
          },
          {
            "ply": 10,
            "san": "Nc3",
            "cp": 43
          },
          {
            "ply": 12,
            "san": "O-O",
            "cp": 42
          },
          {
            "ply": 14,
            "san": "h3",
            "cp": 39
          },
          {
            "ply": 16,
            "san": "Qxd4",
            "cp": 28
          },
          {
            "ply": 18,
            "san": "Bxe6",
            "cp": 24
          }
        ],
        "sources": [
          "CD"
        ]
      },
      {
        "id": "scotch-d6",
        "name": "3...d6 (Scotch declined)",
        "kind": "main",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "Nc6",
          "d4",
          "d6",
          "d5",
          "Nce7",
          "c4",
          "Ng6",
          "Nc3",
          "Nf6",
          "Bd3",
          "Be7",
          "O-O",
          "O-O",
          "h3"
        ],
        "deviatesAt": 5,
        "cp": 53,
        "evals": [
          {
            "ply": 0,
            "san": "e4",
            "cp": 35
          },
          {
            "ply": 2,
            "san": "Nf3",
            "cp": 38
          },
          {
            "ply": 4,
            "san": "d4",
            "cp": 33
          },
          {
            "ply": 6,
            "san": "d5",
            "cp": 78
          },
          {
            "ply": 8,
            "san": "c4",
            "cp": 87
          },
          {
            "ply": 10,
            "san": "Nc3",
            "cp": 96
          },
          {
            "ply": 12,
            "san": "Bd3",
            "cp": 82
          },
          {
            "ply": 14,
            "san": "O-O",
            "cp": 52
          },
          {
            "ply": 16,
            "san": "h3",
            "cp": 53
          }
        ],
        "sources": [
          "W-Scotch",
          "Games"
        ]
      },
      {
        "id": "h6",
        "name": "4...h6 (passive)",
        "kind": "main",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "Nc6",
          "d4",
          "exd4",
          "Bc4",
          "h6",
          "Nxd4",
          "Nf6",
          "Nxc6",
          "bxc6",
          "e5",
          "d5",
          "exf6"
        ],
        "deviatesAt": 7,
        "cp": 39,
        "evals": [
          {
            "ply": 0,
            "san": "e4",
            "cp": 35
          },
          {
            "ply": 2,
            "san": "Nf3",
            "cp": 38
          },
          {
            "ply": 4,
            "san": "d4",
            "cp": 33
          },
          {
            "ply": 6,
            "san": "Bc4",
            "cp": 10
          },
          {
            "ply": 8,
            "san": "Nxd4",
            "cp": 56
          },
          {
            "ply": 10,
            "san": "Nxc6",
            "cp": 55
          },
          {
            "ply": 12,
            "san": "e5",
            "cp": 43
          },
          {
            "ply": 14,
            "san": "exf6",
            "cp": 39
          }
        ],
        "sources": [
          "Games",
          "SF"
        ]
      },
      {
        "id": "haxo-trap",
        "name": "Haxo accepted, 6.Bxf7+!",
        "kind": "side",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "Nc6",
          "d4",
          "exd4",
          "Bc4",
          "Bc5",
          "c3",
          "dxc3",
          "Bxf7+",
          "Kxf7",
          "Qd5+",
          "Kf8",
          "Qxc5+",
          "d6",
          "Qxc3"
        ],
        "deviatesAt": 7,
        "cp": 75,
        "evals": [
          {
            "ply": 0,
            "san": "e4",
            "cp": 35
          },
          {
            "ply": 2,
            "san": "Nf3",
            "cp": 38
          },
          {
            "ply": 4,
            "san": "d4",
            "cp": 33
          },
          {
            "ply": 6,
            "san": "Bc4",
            "cp": 10
          },
          {
            "ply": 8,
            "san": "c3",
            "cp": -2
          },
          {
            "ply": 10,
            "san": "Bxf7+",
            "cp": 74
          },
          {
            "ply": 12,
            "san": "Qd5+",
            "cp": 73
          },
          {
            "ply": 14,
            "san": "Qxc5+",
            "cp": 75
          },
          {
            "ply": 16,
            "san": "Qxc3",
            "cp": 75
          }
        ],
        "sources": [
          "W-Scotch",
          "CD",
          "SF"
        ],
        "claim": "the bishop comes back with the king dragged out; White ahead in development"
      },
      {
        "id": "london-trap",
        "name": "London Defence trap, 6...Bc5?",
        "kind": "side",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "Nc6",
          "d4",
          "exd4",
          "Bc4",
          "Bb4+",
          "c3",
          "dxc3",
          "bxc3",
          "Bc5",
          "Bxf7+",
          "Kxf7",
          "Qd5+",
          "Kf8",
          "Qxc5+",
          "d6",
          "Qc4"
        ],
        "deviatesAt": 7,
        "cp": 94,
        "evals": [
          {
            "ply": 0,
            "san": "e4",
            "cp": 35
          },
          {
            "ply": 2,
            "san": "Nf3",
            "cp": 38
          },
          {
            "ply": 4,
            "san": "d4",
            "cp": 33
          },
          {
            "ply": 6,
            "san": "Bc4",
            "cp": 10
          },
          {
            "ply": 8,
            "san": "c3",
            "cp": 0
          },
          {
            "ply": 10,
            "san": "bxc3",
            "cp": -8
          },
          {
            "ply": 12,
            "san": "Bxf7+",
            "cp": 66
          },
          {
            "ply": 14,
            "san": "Qd5+",
            "cp": 76
          },
          {
            "ply": 16,
            "san": "Qxc5+",
            "cp": 90
          },
          {
            "ply": 18,
            "san": "Qc4",
            "cp": 94
          }
        ],
        "sources": [
          "CD"
        ],
        "claim": "the same Bxf7+ fork wins a piece"
      },
      {
        "id": "lolli",
        "name": "Lolli Variation, 3...Nxd4",
        "kind": "side",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "Nc6",
          "d4",
          "Nxd4",
          "Nxd4",
          "exd4",
          "Qxd4",
          "Ne7",
          "Bc4",
          "Nc6",
          "Qd5",
          "Qf6",
          "O-O",
          "Ne5",
          "Be2"
        ],
        "deviatesAt": 5,
        "cp": 66,
        "evals": [
          {
            "ply": 0,
            "san": "e4",
            "cp": 35
          },
          {
            "ply": 2,
            "san": "Nf3",
            "cp": 38
          },
          {
            "ply": 4,
            "san": "d4",
            "cp": 33
          },
          {
            "ply": 6,
            "san": "Nxd4",
            "cp": 49
          },
          {
            "ply": 8,
            "san": "Qxd4",
            "cp": 62
          },
          {
            "ply": 10,
            "san": "Bc4",
            "cp": 74
          },
          {
            "ply": 12,
            "san": "Qd5",
            "cp": 58
          },
          {
            "ply": 14,
            "san": "O-O",
            "cp": 71
          },
          {
            "ply": 16,
            "san": "Be2",
            "cp": 66
          }
        ],
        "sources": [
          "W-Scotch"
        ],
        "claim": "centralised queen Black cannot chase; small but lasting plus"
      },
      {
        "id": "qf6-4",
        "name": "4...Qf6?!",
        "kind": "side",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "Nc6",
          "d4",
          "exd4",
          "Bc4",
          "Qf6",
          "O-O",
          "d6",
          "c3",
          "d3",
          "Qxd3",
          "Qg6",
          "Na3"
        ],
        "deviatesAt": 7,
        "cp": 80,
        "evals": [
          {
            "ply": 0,
            "san": "e4",
            "cp": 35
          },
          {
            "ply": 2,
            "san": "Nf3",
            "cp": 38
          },
          {
            "ply": 4,
            "san": "d4",
            "cp": 33
          },
          {
            "ply": 6,
            "san": "Bc4",
            "cp": 10
          },
          {
            "ply": 8,
            "san": "O-O",
            "cp": 85
          },
          {
            "ply": 10,
            "san": "c3",
            "cp": 92
          },
          {
            "ply": 12,
            "san": "Qxd3",
            "cp": 73
          },
          {
            "ply": 14,
            "san": "Na3",
            "cp": 80
          }
        ],
        "sources": [
          "Games",
          "SF"
        ],
        "claim": "early queen: develop with tempo"
      },
      {
        "id": "f5",
        "name": "3...f5?!",
        "kind": "side",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "Nc6",
          "d4",
          "f5",
          "Nxe5",
          "Nxe5",
          "dxe5",
          "fxe4",
          "Nc3",
          "Bb4",
          "Qd4",
          "Bxc3+",
          "bxc3"
        ],
        "deviatesAt": 5,
        "cp": 245,
        "evals": [
          {
            "ply": 0,
            "san": "e4",
            "cp": 35
          },
          {
            "ply": 2,
            "san": "Nf3",
            "cp": 38
          },
          {
            "ply": 4,
            "san": "d4",
            "cp": 33
          },
          {
            "ply": 6,
            "san": "Nxe5",
            "cp": 164
          },
          {
            "ply": 8,
            "san": "dxe5",
            "cp": 194
          },
          {
            "ply": 10,
            "san": "Nc3",
            "cp": 198
          },
          {
            "ply": 12,
            "san": "Qd4",
            "cp": 218
          },
          {
            "ply": 14,
            "san": "bxc3",
            "cp": 245
          }
        ],
        "sources": [
          "Games",
          "SF"
        ],
        "claim": "wins a pawn and exposes the king"
      },
      {
        "id": "bd6",
        "name": "3...Bd6?!",
        "kind": "side",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "Nc6",
          "d4",
          "Bd6",
          "d5",
          "Nce7",
          "c4",
          "Bb4+",
          "Nbd2",
          "Nf6",
          "Nxe5",
          "Nxe4",
          "Qf3"
        ],
        "deviatesAt": 5,
        "cp": 59,
        "evals": [
          {
            "ply": 0,
            "san": "e4",
            "cp": 35
          },
          {
            "ply": 2,
            "san": "Nf3",
            "cp": 38
          },
          {
            "ply": 4,
            "san": "d4",
            "cp": 33
          },
          {
            "ply": 6,
            "san": "d5",
            "cp": 82
          },
          {
            "ply": 8,
            "san": "c4",
            "cp": 76
          },
          {
            "ply": 10,
            "san": "Nbd2",
            "cp": 67
          },
          {
            "ply": 12,
            "san": "Nxe5",
            "cp": 60
          },
          {
            "ply": 14,
            "san": "Qf3",
            "cp": 59
          }
        ],
        "sources": [
          "W-Scotch",
          "Games",
          "SF"
        ],
        "claim": "the bishop blocks its own d-pawn; d5 cramps Black"
      },
      {
        "id": "qf6-3",
        "name": "3...Qf6?!",
        "kind": "side",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "Nc6",
          "d4",
          "Qf6",
          "d5",
          "Nb8",
          "Be3",
          "d6",
          "h3",
          "Qd8",
          "Bd3",
          "g6",
          "Nc3"
        ],
        "deviatesAt": 5,
        "cp": 106,
        "evals": [
          {
            "ply": 0,
            "san": "e4",
            "cp": 35
          },
          {
            "ply": 2,
            "san": "Nf3",
            "cp": 38
          },
          {
            "ply": 4,
            "san": "d4",
            "cp": 33
          },
          {
            "ply": 6,
            "san": "d5",
            "cp": 107
          },
          {
            "ply": 8,
            "san": "Be3",
            "cp": 116
          },
          {
            "ply": 10,
            "san": "h3",
            "cp": 111
          },
          {
            "ply": 12,
            "san": "Bd3",
            "cp": 102
          },
          {
            "ply": 14,
            "san": "Nc3",
            "cp": 106
          }
        ],
        "sources": [
          "Games",
          "SF"
        ],
        "claim": "d5 hits the knight and the queen is misplaced"
      },
      {
        "id": "bb4-3",
        "name": "3...Bb4+?!",
        "kind": "side",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "Nc6",
          "d4",
          "Bb4+",
          "c3",
          "Ba5",
          "d5",
          "Nce7",
          "Nxe5",
          "Nf6",
          "Nc4",
          "Bb6",
          "d6"
        ],
        "deviatesAt": 5,
        "cp": 264,
        "evals": [
          {
            "ply": 0,
            "san": "e4",
            "cp": 35
          },
          {
            "ply": 2,
            "san": "Nf3",
            "cp": 38
          },
          {
            "ply": 4,
            "san": "d4",
            "cp": 33
          },
          {
            "ply": 6,
            "san": "c3",
            "cp": 162
          },
          {
            "ply": 8,
            "san": "d5",
            "cp": 200
          },
          {
            "ply": 10,
            "san": "Nxe5",
            "cp": 225
          },
          {
            "ply": 12,
            "san": "Nc4",
            "cp": 248
          },
          {
            "ply": 14,
            "san": "d6",
            "cp": 264
          }
        ],
        "sources": [
          "Games",
          "SF"
        ],
        "claim": "the bishop is kicked around while White develops"
      }
    ]
  },
  {
    "id": "elephant",
    "name": "Elephant Gambit",
    "side": "b",
    "signaturePlies": 4,
    "lines": [
      {
        "id": "main",
        "name": "Paulsen Countergambit",
        "kind": "main",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "d5",
          "exd5",
          "e4",
          "Qe2",
          "Nf6",
          "d3",
          "Qxd5",
          "Nbd2",
          "Be7",
          "dxe4",
          "Qe6",
          "Nb3",
          "Qxe4",
          "Qxe4",
          "Nxe4"
        ],
        "cp": -52,
        "evals": [
          {
            "ply": 1,
            "san": "e5",
            "cp": -39
          },
          {
            "ply": 3,
            "san": "d5",
            "cp": -84
          },
          {
            "ply": 5,
            "san": "e4",
            "cp": -92
          },
          {
            "ply": 7,
            "san": "Nf6",
            "cp": -83
          },
          {
            "ply": 9,
            "san": "Qxd5",
            "cp": -87
          },
          {
            "ply": 11,
            "san": "Be7",
            "cp": -118
          },
          {
            "ply": 13,
            "san": "Qe6",
            "cp": -120
          },
          {
            "ply": 15,
            "san": "Qxe4",
            "cp": -49
          },
          {
            "ply": 17,
            "san": "Nxe4",
            "cp": -52
          }
        ],
        "sources": [
          "W-Eleph",
          "CM",
          "Lichess",
          "SF"
        ]
      },
      {
        "id": "nc3-5",
        "name": "5.Nc3 (avoids the pin)",
        "kind": "main",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "d5",
          "exd5",
          "e4",
          "Qe2",
          "Nf6",
          "Nc3",
          "Be7",
          "Nxe4",
          "O-O",
          "Nxf6+",
          "Bxf6",
          "Qc4",
          "Re8+",
          "Be2",
          "b5"
        ],
        "deviatesAt": 8,
        "cp": 46,
        "evals": [
          {
            "ply": 1,
            "san": "e5",
            "cp": -39
          },
          {
            "ply": 3,
            "san": "d5",
            "cp": -84
          },
          {
            "ply": 5,
            "san": "e4",
            "cp": -92
          },
          {
            "ply": 7,
            "san": "Nf6",
            "cp": -83
          },
          {
            "ply": 9,
            "san": "Be7",
            "cp": -75
          },
          {
            "ply": 11,
            "san": "O-O",
            "cp": -98
          },
          {
            "ply": 13,
            "san": "Bxf6",
            "cp": -102
          },
          {
            "ply": 15,
            "san": "Re8+",
            "cp": 52
          },
          {
            "ply": 17,
            "san": "b5",
            "cp": 46
          }
        ],
        "sources": [
          "W-Eleph",
          "CM",
          "SF"
        ]
      },
      {
        "id": "nc3-6",
        "name": "6.Nc3 Bb4!",
        "kind": "main",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "d5",
          "exd5",
          "e4",
          "Qe2",
          "Nf6",
          "d3",
          "Qxd5",
          "Nc3",
          "Bb4",
          "Bd2",
          "Bxc3",
          "Bxc3",
          "O-O",
          "dxe4"
        ],
        "deviatesAt": 10,
        "cp": 0,
        "evals": [
          {
            "ply": 1,
            "san": "e5",
            "cp": -39
          },
          {
            "ply": 3,
            "san": "d5",
            "cp": -84
          },
          {
            "ply": 5,
            "san": "e4",
            "cp": -92
          },
          {
            "ply": 7,
            "san": "Nf6",
            "cp": -83
          },
          {
            "ply": 9,
            "san": "Qxd5",
            "cp": -87
          },
          {
            "ply": 11,
            "san": "Bb4",
            "cp": -77
          },
          {
            "ply": 13,
            "san": "Bxc3",
            "cp": -17
          },
          {
            "ply": 15,
            "san": "O-O",
            "cp": 0
          }
        ],
        "sources": [
          "CM",
          "Games",
          "SF"
        ]
      },
      {
        "id": "dxe4-6",
        "name": "6.dxe4 queen trade",
        "kind": "main",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "d5",
          "exd5",
          "e4",
          "Qe2",
          "Nf6",
          "d3",
          "Qxd5",
          "dxe4",
          "Qxe4",
          "Qxe4+",
          "Nxe4",
          "Bd3",
          "Nc5",
          "Bb5+",
          "c6",
          "Be2",
          "Nba6"
        ],
        "deviatesAt": 10,
        "cp": -33,
        "evals": [
          {
            "ply": 1,
            "san": "e5",
            "cp": -39
          },
          {
            "ply": 3,
            "san": "d5",
            "cp": -84
          },
          {
            "ply": 5,
            "san": "e4",
            "cp": -92
          },
          {
            "ply": 7,
            "san": "Nf6",
            "cp": -83
          },
          {
            "ply": 9,
            "san": "Qxd5",
            "cp": -87
          },
          {
            "ply": 11,
            "san": "Qxe4",
            "cp": -37
          },
          {
            "ply": 13,
            "san": "Nxe4",
            "cp": -25
          },
          {
            "ply": 15,
            "san": "Nc5",
            "cp": -27
          },
          {
            "ply": 17,
            "san": "c6",
            "cp": -33
          },
          {
            "ply": 19,
            "san": "Nba6",
            "cp": -33
          }
        ],
        "sources": [
          "Games"
        ]
      },
      {
        "id": "ne5",
        "name": "4.Ne5",
        "kind": "main",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "d5",
          "exd5",
          "e4",
          "Ne5",
          "Qxd5",
          "d4",
          "exd3",
          "Nxd3",
          "Nc6",
          "Nc3",
          "Qa5",
          "Be2",
          "Bf5"
        ],
        "deviatesAt": 6,
        "cp": -20,
        "evals": [
          {
            "ply": 1,
            "san": "e5",
            "cp": -39
          },
          {
            "ply": 3,
            "san": "d5",
            "cp": -84
          },
          {
            "ply": 5,
            "san": "e4",
            "cp": -92
          },
          {
            "ply": 7,
            "san": "Qxd5",
            "cp": -19
          },
          {
            "ply": 9,
            "san": "exd3",
            "cp": -23
          },
          {
            "ply": 11,
            "san": "Nc6",
            "cp": -28
          },
          {
            "ply": 13,
            "san": "Qa5",
            "cp": -6
          },
          {
            "ply": 15,
            "san": "Bf5",
            "cp": -20
          }
        ],
        "sources": [
          "W-Eleph",
          "Games",
          "SF"
        ]
      },
      {
        "id": "nd4",
        "name": "4.Nd4",
        "kind": "main",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "d5",
          "exd5",
          "e4",
          "Nd4",
          "Qxd5",
          "c3",
          "Nc6",
          "Nb5",
          "Qe5",
          "Qe2",
          "Qe7",
          "d4",
          "a6"
        ],
        "deviatesAt": 6,
        "cp": 45,
        "evals": [
          {
            "ply": 1,
            "san": "e5",
            "cp": -39
          },
          {
            "ply": 3,
            "san": "d5",
            "cp": -84
          },
          {
            "ply": 5,
            "san": "e4",
            "cp": -92
          },
          {
            "ply": 7,
            "san": "Qxd5",
            "cp": 10
          },
          {
            "ply": 9,
            "san": "Nc6",
            "cp": 52
          },
          {
            "ply": 11,
            "san": "Qe5",
            "cp": 65
          },
          {
            "ply": 13,
            "san": "Qe7",
            "cp": 61
          },
          {
            "ply": 15,
            "san": "a6",
            "cp": 45
          }
        ],
        "sources": [
          "Games",
          "SF"
        ]
      },
      {
        "id": "ng5",
        "name": "5.Ng5",
        "kind": "main",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "d5",
          "exd5",
          "e4",
          "Qe2",
          "Nf6",
          "Ng5",
          "Be7",
          "Nxe4",
          "O-O",
          "Nxf6+",
          "Bxf6",
          "Qf3",
          "Re8+"
        ],
        "deviatesAt": 8,
        "cp": -39,
        "evals": [
          {
            "ply": 1,
            "san": "e5",
            "cp": -39
          },
          {
            "ply": 3,
            "san": "d5",
            "cp": -84
          },
          {
            "ply": 5,
            "san": "e4",
            "cp": -92
          },
          {
            "ply": 7,
            "san": "Nf6",
            "cp": -83
          },
          {
            "ply": 9,
            "san": "Be7",
            "cp": -8
          },
          {
            "ply": 11,
            "san": "O-O",
            "cp": -43
          },
          {
            "ply": 13,
            "san": "Bxf6",
            "cp": -47
          },
          {
            "ply": 15,
            "san": "Re8+",
            "cp": -39
          }
        ],
        "sources": [
          "Games",
          "SF"
        ]
      },
      {
        "id": "nxe5",
        "name": "3.Nxe5 Bd6",
        "kind": "main",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "d5",
          "Nxe5",
          "Bd6",
          "d4",
          "dxe4",
          "Bc4",
          "Bxe5",
          "Qh5",
          "Qe7",
          "Qxe5",
          "Qxe5",
          "dxe5",
          "Nc6"
        ],
        "deviatesAt": 4,
        "cp": -70,
        "evals": [
          {
            "ply": 1,
            "san": "e5",
            "cp": -39
          },
          {
            "ply": 3,
            "san": "d5",
            "cp": -84
          },
          {
            "ply": 5,
            "san": "Bd6",
            "cp": -68
          },
          {
            "ply": 7,
            "san": "dxe4",
            "cp": -74
          },
          {
            "ply": 9,
            "san": "Bxe5",
            "cp": -64
          },
          {
            "ply": 11,
            "san": "Qe7",
            "cp": -74
          },
          {
            "ply": 13,
            "san": "Qxe5",
            "cp": -73
          },
          {
            "ply": 15,
            "san": "Nc6",
            "cp": -70
          }
        ],
        "sources": [
          "W-Eleph",
          "CM",
          "Lichess",
          "Games",
          "SF"
        ]
      },
      {
        "id": "nxe5-nf3",
        "name": "3.Nxe5 Bd6 4.Nf3 (retreat)",
        "kind": "main",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "d5",
          "Nxe5",
          "Bd6",
          "Nf3",
          "dxe4",
          "Nd4",
          "Nf6",
          "d3",
          "O-O",
          "dxe4",
          "Nxe4"
        ],
        "deviatesAt": 4,
        "cp": 74,
        "evals": [
          {
            "ply": 1,
            "san": "e5",
            "cp": -39
          },
          {
            "ply": 3,
            "san": "d5",
            "cp": -84
          },
          {
            "ply": 5,
            "san": "Bd6",
            "cp": -68
          },
          {
            "ply": 7,
            "san": "dxe4",
            "cp": 92
          },
          {
            "ply": 9,
            "san": "Nf6",
            "cp": 84
          },
          {
            "ply": 11,
            "san": "O-O",
            "cp": 72
          },
          {
            "ply": 13,
            "san": "Nxe4",
            "cp": 74
          }
        ],
        "sources": [
          "Games",
          "SF"
        ]
      },
      {
        "id": "d4",
        "name": "3.d4 (Elephant declined)",
        "kind": "main",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "d5",
          "d4",
          "dxe4",
          "Nxe5",
          "Nd7",
          "Nxd7",
          "Bxd7",
          "Bc4",
          "Nf6",
          "Nc3",
          "Be7",
          "O-O",
          "Bg4"
        ],
        "deviatesAt": 4,
        "cp": -3,
        "evals": [
          {
            "ply": 1,
            "san": "e5",
            "cp": -39
          },
          {
            "ply": 3,
            "san": "d5",
            "cp": -84
          },
          {
            "ply": 5,
            "san": "dxe4",
            "cp": -52
          },
          {
            "ply": 7,
            "san": "Nd7",
            "cp": -61
          },
          {
            "ply": 9,
            "san": "Bxd7",
            "cp": -27
          },
          {
            "ply": 11,
            "san": "Nf6",
            "cp": -20
          },
          {
            "ply": 13,
            "san": "Be7",
            "cp": -5
          },
          {
            "ply": 15,
            "san": "Bg4",
            "cp": -3
          }
        ],
        "sources": [
          "Games",
          "SF"
        ]
      },
      {
        "id": "d3",
        "name": "3.d3 (quiet)",
        "kind": "main",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "d5",
          "d3",
          "dxe4",
          "dxe4",
          "Qxd1+",
          "Kxd1",
          "Nf6",
          "Nc3",
          "Bc5",
          "Nxe5",
          "Bxf2",
          "Nd5",
          "Nxd5"
        ],
        "deviatesAt": 4,
        "cp": 29,
        "evals": [
          {
            "ply": 1,
            "san": "e5",
            "cp": -39
          },
          {
            "ply": 3,
            "san": "d5",
            "cp": -84
          },
          {
            "ply": 5,
            "san": "dxe4",
            "cp": 2
          },
          {
            "ply": 7,
            "san": "Qxd1+",
            "cp": 8
          },
          {
            "ply": 9,
            "san": "Nf6",
            "cp": 16
          },
          {
            "ply": 11,
            "san": "Bc5",
            "cp": 13
          },
          {
            "ply": 13,
            "san": "Bxf2",
            "cp": 9
          },
          {
            "ply": 15,
            "san": "Nxd5",
            "cp": 29
          }
        ],
        "sources": [
          "Games",
          "SF"
        ]
      },
      {
        "id": "nc3-3",
        "name": "3.Nc3",
        "kind": "main",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "d5",
          "Nc3",
          "dxe4",
          "Nxe4",
          "Nc6",
          "Bb5",
          "Bd7",
          "O-O",
          "Nf6",
          "Re1",
          "Nxe4",
          "Rxe4",
          "Be7"
        ],
        "deviatesAt": 4,
        "cp": -65,
        "evals": [
          {
            "ply": 1,
            "san": "e5",
            "cp": -39
          },
          {
            "ply": 3,
            "san": "d5",
            "cp": -84
          },
          {
            "ply": 5,
            "san": "dxe4",
            "cp": 0
          },
          {
            "ply": 7,
            "san": "Nc6",
            "cp": -35
          },
          {
            "ply": 9,
            "san": "Bd7",
            "cp": -75
          },
          {
            "ply": 11,
            "san": "Nf6",
            "cp": -67
          },
          {
            "ply": 13,
            "san": "Nxe4",
            "cp": -64
          },
          {
            "ply": 15,
            "san": "Be7",
            "cp": -65
          }
        ],
        "sources": [
          "W-Eleph",
          "SF"
        ]
      },
      {
        "id": "ng1",
        "name": "4.Ng1 full retreat",
        "kind": "main",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "d5",
          "exd5",
          "e4",
          "Ng1",
          "Qxd5",
          "d4",
          "Nc6",
          "Be3",
          "Nf6",
          "c4",
          "Qf5"
        ],
        "deviatesAt": 6,
        "cp": -34,
        "evals": [
          {
            "ply": 1,
            "san": "e5",
            "cp": -39
          },
          {
            "ply": 3,
            "san": "d5",
            "cp": -84
          },
          {
            "ply": 5,
            "san": "e4",
            "cp": -92
          },
          {
            "ply": 7,
            "san": "Qxd5",
            "cp": -9
          },
          {
            "ply": 9,
            "san": "Nc6",
            "cp": 0
          },
          {
            "ply": 11,
            "san": "Nf6",
            "cp": -17
          },
          {
            "ply": 13,
            "san": "Qf5",
            "cp": -34
          }
        ],
        "sources": [
          "Games",
          "SF"
        ]
      },
      {
        "id": "bb5",
        "name": "4.Bb5+ c6!",
        "kind": "side",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "d5",
          "exd5",
          "e4",
          "Bb5+",
          "c6",
          "dxc6",
          "bxc6",
          "Bc4",
          "exf3",
          "Qxf3",
          "Nf6"
        ],
        "deviatesAt": 6,
        "cp": 195,
        "evals": [
          {
            "ply": 1,
            "san": "e5",
            "cp": -39
          },
          {
            "ply": 3,
            "san": "d5",
            "cp": -84
          },
          {
            "ply": 5,
            "san": "e4",
            "cp": -92
          },
          {
            "ply": 7,
            "san": "c6",
            "cp": 196
          },
          {
            "ply": 9,
            "san": "bxc6",
            "cp": 199
          },
          {
            "ply": 11,
            "san": "exf3",
            "cp": 194
          },
          {
            "ply": 13,
            "san": "Nf6",
            "cp": 195
          }
        ],
        "sources": [
          "Games",
          "Lichess"
        ],
        "claim": "the check achieves nothing; ...exf3 follows and Black is better"
      },
      {
        "id": "bd3",
        "name": "3.Bd3?! blocks the d-pawn",
        "kind": "side",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "d5",
          "Bd3",
          "dxe4",
          "Bxe4",
          "f5",
          "Bd3",
          "e4",
          "Bb5+",
          "c6",
          "Bc4",
          "exf3"
        ],
        "deviatesAt": 4,
        "cp": 188,
        "evals": [
          {
            "ply": 1,
            "san": "e5",
            "cp": -39
          },
          {
            "ply": 3,
            "san": "d5",
            "cp": -84
          },
          {
            "ply": 5,
            "san": "dxe4",
            "cp": 205
          },
          {
            "ply": 7,
            "san": "f5",
            "cp": 209
          },
          {
            "ply": 9,
            "san": "e4",
            "cp": 215
          },
          {
            "ply": 11,
            "san": "c6",
            "cp": 162
          },
          {
            "ply": 13,
            "san": "exf3",
            "cp": 188
          }
        ],
        "sources": [
          "Games",
          "SF"
        ],
        "claim": "take with tempo; White’s development is knotted"
      },
      {
        "id": "nc4",
        "name": "3.Nxe5 Bd6 4.Nc4?!",
        "kind": "side",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "d5",
          "Nxe5",
          "Bd6",
          "Nc4",
          "dxc4",
          "Bxc4",
          "Qh4",
          "d3",
          "Nf6",
          "h3",
          "Nc6"
        ],
        "deviatesAt": 4,
        "cp": 250,
        "evals": [
          {
            "ply": 1,
            "san": "e5",
            "cp": -39
          },
          {
            "ply": 3,
            "san": "d5",
            "cp": -84
          },
          {
            "ply": 5,
            "san": "Bd6",
            "cp": -68
          },
          {
            "ply": 7,
            "san": "dxc4",
            "cp": 224
          },
          {
            "ply": 9,
            "san": "Qh4",
            "cp": 238
          },
          {
            "ply": 11,
            "san": "Nf6",
            "cp": 242
          },
          {
            "ply": 13,
            "san": "Nc6",
            "cp": 250
          }
        ],
        "sources": [
          "CB",
          "SF"
        ],
        "claim": "the knight wanders to c4 and gets hit; Black develops with tempo"
      },
      {
        "id": "nxf7",
        "name": "3.Nxe5 Bd6 4.Nxf7?! (greedy)",
        "kind": "side",
        "moves": [
          "e4",
          "e5",
          "Nf3",
          "d5",
          "Nxe5",
          "Bd6",
          "Nxf7",
          "Kxf7",
          "e5",
          "Bxe5",
          "Qh5+",
          "Ke6",
          "Qe2",
          "Kd6"
        ],
        "deviatesAt": 4,
        "cp": 159,
        "evals": [
          {
            "ply": 1,
            "san": "e5",
            "cp": -39
          },
          {
            "ply": 3,
            "san": "d5",
            "cp": -84
          },
          {
            "ply": 5,
            "san": "Bd6",
            "cp": -68
          },
          {
            "ply": 7,
            "san": "Kxf7",
            "cp": 131
          },
          {
            "ply": 9,
            "san": "Bxe5",
            "cp": 162
          },
          {
            "ply": 11,
            "san": "Ke6",
            "cp": 150
          },
          {
            "ply": 13,
            "san": "Kd6",
            "cp": 159
          }
        ],
        "sources": [
          "Games",
          "Lichess",
          "SF"
        ],
        "claim": "the knight fork gets a rook for two pieces? no — Black scores 60% here in practice"
      }
    ]
  }
];

