/* ---------------------------------------------------------------
   THE REPERTOIRE — two openings, each a bundle of named LINES.

   Vocabulary used everywhere in this project:
   - SAN  = Standard Algebraic Notation for one move: "Nf3", "exd4", "O-O".
   - ply  = one half-move. moves[0] is White's first move (ply 0),
            moves[1] is Black's reply (ply 1), and so on.
            Even plies are always White, odd plies are always Black.

   Shape (see js/tree.js):
     { id, name, side, signaturePlies, lines: [
         { id, name, kind: 'main' | 'side', moves, deviatesAt, games, cp, swing, verdict, reason, note } ] }
   - lines[0] is the TRUNK: master theory, hand-approved.
   - 'main' lines are sound opponent alternatives you must know.
   - 'side' lines are opponent mistakes with the punishment worked out.

   WHERE THE DATA COMES FROM
   - js/repertoire.data.js is GENERATED by tools/build-repertoire.mjs from
     stas1928's last 6 months of Chess.com games + Stockfish 18 (depth 14):
     every opponent reply that appeared twice or more becomes a line; the
     engine decides whether it is a sound variation or a mistake, plays our
     moves, and cuts side lines by the brief's rule (≥ 4 of our moves).
     Opponent moves inside lines are what YOUR opponents most often play.
   - js/notes.js holds the human explanations and survives regeneration.
   Regenerate with:  node tools/build-repertoire.mjs stas1928 6 14 > tmp.json
   then paste into repertoire.data.js. Never hand-edit the data file.

   The tests in tests/repertoire.test.mjs prove every move is legal, in the
   exact SAN chess.js produces, and that our side plays ONE move per
   position across all lines.
--------------------------------------------------------------- */
import DATA from './repertoire.data.js';
import { NOTES } from './notes.js';
import { moveLabel } from './tree.js';

function autoNote(opening, line) {
  const you = (cp) => `${cp >= 0 ? '+' : '−'}${Math.abs(cp / 100).toFixed(1)}`;
  const parts = [];
  if (line.games) parts.push(`Seen ${line.games}× in your games.`);
  if (line.kind === 'side') parts.push(`Engine: ${line.reason ?? `opponent's move costs them ${you(line.swing ?? 0)}`}.`);
  else if (line.deviatesAt !== undefined) parts.push(`Engine: a sound choice — you stand ${you(line.cp ?? 0)} at the end of the line.`);
  return parts.join(' ');
}

export const OPENINGS = DATA.map((o) => ({
  ...o,
  lines: o.lines.map((l) => ({
    ...l,
    note: NOTES[o.id]?.[l.id] ?? autoNote(o, l),
  })),
}));

/** Look an opening up by its id ("scotch" / "elephant"). */
export function getOpening(id) {
  const opening = OPENINGS.find((o) => o.id === id);
  if (!opening) throw new Error(`Unknown opening: ${id}`);
  return opening;
}

/** Short label for a line in lists: "3...d6 · 3...d6 line" -> "3...d6 line". */
export function lineTitle(line) {
  if (line.deviatesAt === undefined || line.deviatesAt === null) return line.name;
  const label = moveLabel(line.deviatesAt, line.moves[line.deviatesAt]);
  return line.name.startsWith(label) ? line.name : `${label} · ${line.name}`;
}
