/* ---------------------------------------------------------------
   Build the coach dialog for every shipped ply.
     why  = sourced idea from library/ideas.mjs if present,
            else board facts (js/facts.js) + an unmistakable engine threat.
     say  = library/ideas.mjs `say` if present, else js/coach.js voice.
     marks = teaching arrows / circles.
   Engine threats (null-move, depth 12) are cached in
   library/ideas-threats.json so re-runs are instant and deterministic.
   Writes js/ideas.data.js (GENERATED) and docs/COACH.md (review copy).
   Usage: node tools/build-ideas.mjs [--no-engine]
--------------------------------------------------------------- */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { Chess } from '../vendor/chess.js';
import REPERTOIRE from '../js/repertoire.data.js';
import { moveFacts, VALUE } from '../js/facts.js';
import { coachSay, defaultWhy, factMarks, ownThreat } from '../js/coach.js';
import { IDEAS } from '../library/ideas.mjs';
import { NAMES } from '../js/names.js';

const TH = new URL('../library/ideas-threats.json', import.meta.url);
const threats = existsSync(TH) ? JSON.parse(readFileSync(TH, 'utf8')) : {};
const useEngine = !process.argv.includes('--no-engine');
let engine = null;

/** Null-move threat: give the mover a second move; is there a capture winning >= 1.5 pawns, or mate? */
async function threatFor(before, san, f) {
  const key = [...before, san].join(' ');
  if (key in threats) return threats[key];
  if (!useEngine || f.check) return (threats[key] = null);
  engine ??= await (await import('./nodeEngine.mjs')).createNodeEngine({ defaultDepth: 12 });
  const g = new Chess();
  for (const s of [...before, san]) g.move(s);
  const fen = g.fen().split(' ');
  const nullFen = [fen[0], fen[1] === 'w' ? 'b' : 'w', fen[2], '-', '0', fen[5]].join(' ');
  const sign = f.side === 'w' ? 1 : -1;
  const real = await engine.evaluateFen(g.fen());
  const nul = await engine.evaluateFen(nullFen);
  const bm = nul.bestMove;
  let t = null;
  if (nul.mate != null && sign * nul.mate > 0 && Math.abs(nul.mate) <= 2) t = { mate: true, from: bm?.from, to: bm?.to };
  else if (bm?.captured && nul.cp != null && real.cp != null && sign * (nul.cp - real.cp) >= 150 && VALUE[bm.captured] >= 1) {
    t = { from: bm.from, to: bm.to, piece: bm.piece, captured: bm.captured };
  }
  return (threats[key] = t);
}

const out = {};
const doc = ['# Coach dialog — review copy', '', 'GENERATED by tools/build-ideas.mjs. Source: `why` from a named source (src), else board facts (`position`), plus an engine threat (`sf`) only when unmistakable. Text only — no sound.', ''];
let counts = { sourced: 0, sf: 0, position: 0 };
for (const o of REPERTOIRE) {
  doc.push(`## ${o.name}`, '');
  const seen = new Set();
  for (const l of [...o.lines, ...(o.surprise ?? [])]) {
    const rows = [];
    for (let i = 0; i < l.moves.length; i++) {
      const before = l.moves.slice(0, i), san = l.moves[i];
      const key = [...before, san].join(' ');
      const mine = (o.side === 'w') === (i % 2 === 0);
      if (!seen.has(key)) {
        seen.add(key);
        const f = moveFacts(before, san);
        const threat = await threatFor(before, san, f);
        const src = IDEAS[key];
        const why = src?.why ?? defaultWhy(f, threat);
        const say = src?.say ?? coachSay(f, { mine, key, threat });
        const marks = src?.marks ?? factMarks(f, threat);
        const from = src ? src.src : ownThreat(f, threat) ? ['position', 'sf'] : ['position'];
        counts[src ? 'sourced' : ownThreat(f, threat) ? 'sf' : 'position']++;
        out[key] = { say, why, src: from, ...(marks.arrows.length || marks.circles.length ? { marks } : {}) };
        rows.push(`| ${Math.floor(i / 2) + 1}${i % 2 ? '…' : '.'}${san} | ${mine ? '**we**' : 'they'} | ${say} | ${why} | ${from.join(', ')} |`);
      }
    }
    if (rows.length) doc.push(`### ${NAMES[o.id]?.[l.id] ?? l.name}`, '', '| move | who | coach says | why | source |', '|---|---|---|---|---|', ...rows, '');
  }
}
engine?.stop();
const unused = Object.keys(IDEAS).filter((k) => !(k in out));
if (unused.length) console.log('IDEAS keys not on any shipped line (typo?): ' + unused.join(' | '));
writeFileSync(TH, JSON.stringify(threats, null, 1) + '\n');
writeFileSync(new URL('../js/ideas.data.js', import.meta.url),
  `/* GENERATED by tools/build-ideas.mjs from library/ideas.mjs + js/facts.js + library/ideas-threats.json — do not edit by hand. */\nexport default ${JSON.stringify(out, null, 1)};\n`);
writeFileSync(new URL('../docs/COACH.md', import.meta.url), doc.join('\n') + '\n');
console.log(`plies: ${Object.keys(out).length} — sourced ${counts.sourced}, engine threat ${counts.sf}, board facts ${counts.position}`);
